apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  labels:
    app: simple-app-argocd
spec:
  type: ClusterIP
  selector:
    app: simple-app-argocd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
